version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto8
  build:
    commands:
      - mvn clean
  post_build:
    commands:
      - mvn package
      - mv target/jacob_brummett_p1-1.0.war ROOT.war
artifacts:
  files:
    - ROOT.war
